/**
 * model/Arete.java
 *
 * File generated from the Arete uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 2/26/14 2:00:37 PM (February 26, 2014) $
 */
package model;

// Start of user code to add imports for Arete
 

// End of user code

/**
 * Description of the class Arete.
 *
 */

public class Arete {
		private double distance;
		private Case extr;
		private Case orig;
		
		// Start of user code to add fields for Arete
		 
		// End of user code
		
		/**
		 * Constructor.
		 */
		public Arete() {
			// Start of user code for constructor Arete
			super();
			// End of user code
		}
		
		/**
		 * Return distance.
		 * @return distance
		 */
		public double getDistance() {
		    return distance;
		}
		
		/**
		 * Set a value to attribute distance.
		 * @param distance
		 */
		public void setDistance(double distance) {
		    this.distance = distance;
		}
		
		/**
		 * Return extr.
		 * @return extr
		 */
		public Case getExtr() {
		    return extr;
		}
		
		/**
		 * Set a value to attribute extr.
		 * @param extr
		 */
		public void setExtr(Case extr) {
		    this.extr = extr;
		}
		
		/**
		 * Return orig.
		 * @return orig
		 */
		public Case getOrig() {
		    return orig;
		}
		
		/**
		 * Set a value to attribute orig.
		 * @param orig
		 */
		public void setOrig(Case orig) {
		    this.orig = orig;
		}
		
		
		
		// Start of user code to add methods for Arete
		
		// End of user code
}