/**
 * model/Case.java
 *
 * File generated from the Case uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 2/26/14 2:00:36 PM (February 26, 2014) $
 */
package model;

// Start of user code to add imports for Case
 

// End of user code

/**
 * Description of the class Case.
 *
 */

public class Case {
		
		// Start of user code to add fields for Case
		 
		// End of user code
		
		/**
		 * Constructor.
		 */
		public Case() {
			// Start of user code for constructor Case
			super();
			// End of user code
		}
		
		
		
		// Start of user code to add methods for Case
		
		// End of user code
}