/**
 * model/CaseObstacle.java
 *
 * File generated from the CaseObstacle uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 2/26/14 2:00:36 PM (February 26, 2014) $
 */
package model;

// Start of user code to add imports for CaseObstacle
 

// End of user code

/**
 * Description of the class CaseObstacle.
 *
 */

public class CaseObstacle extends Case {
		private Obstacle obstacle;
		
		// Start of user code to add fields for CaseObstacle
		 
		// End of user code
		
		/**
		 * Constructor.
		 */
		public CaseObstacle() {
			// Start of user code for constructor CaseObstacle
			super();
			// End of user code
		}
		
		/**
		 * Return obstacle.
		 * @return obstacle
		 */
		public Obstacle getObstacle() {
		    return obstacle;
		}
		
		/**
		 * Set a value to attribute obstacle.
		 * @param obstacle
		 */
		public void setObstacle(Obstacle obstacle) {
		    this.obstacle = obstacle;
		}
		
		
		
		// Start of user code to add methods for CaseObstacle
		
		// End of user code
}