/**
 * model/CaseLibre.java
 *
 * File generated from the CaseLibre uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 2/26/14 2:00:36 PM (February 26, 2014) $
 */
package model;

// Start of user code to add imports for CaseLibre
 
import java.util.HashSet;

// End of user code

/**
 * Description of the class CaseLibre.
 *
 */

public class CaseLibre extends Case {
		private HashSet<UniteLibre> unites;
		
		// Start of user code to add fields for CaseLibre
		 
		// End of user code
		
		/**
		 * Constructor.
		 */
		public CaseLibre() {
			// Start of user code for constructor CaseLibre
			super();
			// End of user code
		}
		
		/**
		 * Return unites.
		 * @return unites
		 */
		public HashSet<UniteLibre> getUnites() {
		    return unites;
		}
		
		/**
		 * Set a value to attribute unites.
		 * @param unites.
		 */
		public void setUnites(HashSet<UniteLibre> unites) {
		    this.unites = unites;
		}
		
		/**
		 * Add a unites to the unites collection.
		 * @param unites_elt Element to add.
		 */
		public void addUnites(UniteLibre unites_elt) {
		    this.unites.add(unites_elt);
		}
		
		/**
		 * Remove a unites to the unites collection.
		 * @param unites_elt Element to remove
		 */
		public void removeUnites(UniteLibre unites_elt) {
		    this.unites.remove(unites_elt);
		}
		
		
		/**
		 * Description of the method estPleine.
		 *
		 * @return ret
		 */
		public boolean estPleine() {
			// Start of user code for method estPleine

			boolean ret = false;

			return ret;
			// End of user code
		}
		
		// Start of user code to add methods for CaseLibre
		
		// End of user code
}