/**
 * model/Obstacle.java
 *
 * File generated from the Obstacle uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 2/26/14 2:00:37 PM (February 26, 2014) $
 */
package model;

// Start of user code to add imports for Obstacle
 

// End of user code

/**
 * Description of the class Obstacle.
 *
 */

public class Obstacle {
		
		// Start of user code to add fields for Obstacle
		 
		// End of user code
		
		/**
		 * Constructor.
		 */
		public Obstacle() {
			// Start of user code for constructor Obstacle
			super();
			// End of user code
		}
		
		
		
		// Start of user code to add methods for Obstacle
		
		// End of user code
}