/**
 * model/Position.java
 *
 * File generated from the Position uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 2/26/14 2:00:36 PM (February 26, 2014) $
 */
package model;

// Start of user code to add imports for Position
 

// End of user code

/**
 * Description of the class Position.
 *
 */

public class Position {
		private int posX;
		private int posY;
		
		// Start of user code to add fields for Position
		 
		// End of user code
		
		/**
		 * Constructor.
		 */
		public Position() {
			// Start of user code for constructor Position
			super();
			// End of user code
		}
		
		/**
		 * Return posX.
		 * @return posX
		 */
		public int getPosX() {
		    return posX;
		}
		
		/**
		 * Set a value to attribute posX.
		 * @param posX
		 */
		public void setPosX(int posX) {
		    this.posX = posX;
		}
		
		/**
		 * Return posY.
		 * @return posY
		 */
		public int getPosY() {
		    return posY;
		}
		
		/**
		 * Set a value to attribute posY.
		 * @param posY
		 */
		public void setPosY(int posY) {
		    this.posY = posY;
		}
		
		
		
		// Start of user code to add methods for Position
		
		// End of user code
}