/**
 * model/Unite.java
 *
 * File generated from the Unite uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 2/26/14 2:00:36 PM (February 26, 2014) $
 */
package model;

// Start of user code to add imports for Unite
 

// End of user code

/**
 * Description of the class Unite.
 *
 */

public class Unite {
		protected int pvRestant;
		protected int pointAttaque;
		protected double porteeAttaque;
		protected int taille;
		protected int vitesseAttaque;
		protected double porteeVision;
		
		// Start of user code to add fields for Unite
		 
		// End of user code
		
		/**
		 * Constructor.
		 */
		public Unite() {
			// Start of user code for constructor Unite
			super();
			// End of user code
		}
		
		/**
		 * Return pvRestant.
		 * @return pvRestant
		 */
		public int getPvRestant() {
		    return pvRestant;
		}
		
		/**
		 * Set a value to attribute pvRestant.
		 * @param pvRestant
		 */
		public void setPvRestant(int pvRestant) {
		    this.pvRestant = pvRestant;
		}
		
		/**
		 * Return pointAttaque.
		 * @return pointAttaque
		 */
		public int getPointAttaque() {
		    return pointAttaque;
		}
		
		/**
		 * Set a value to attribute pointAttaque.
		 * @param pointAttaque
		 */
		public void setPointAttaque(int pointAttaque) {
		    this.pointAttaque = pointAttaque;
		}
		
		/**
		 * Return porteeAttaque.
		 * @return porteeAttaque
		 */
		public double getPorteeAttaque() {
		    return porteeAttaque;
		}
		
		/**
		 * Set a value to attribute porteeAttaque.
		 * @param porteeAttaque
		 */
		public void setPorteeAttaque(double porteeAttaque) {
		    this.porteeAttaque = porteeAttaque;
		}
		
		/**
		 * Return taille.
		 * @return taille
		 */
		public int getTaille() {
		    return taille;
		}
		
		/**
		 * Set a value to attribute taille.
		 * @param taille
		 */
		public void setTaille(int taille) {
		    this.taille = taille;
		}
		
		/**
		 * Return vitesseAttaque.
		 * @return vitesseAttaque
		 */
		public int getVitesseAttaque() {
		    return vitesseAttaque;
		}
		
		/**
		 * Set a value to attribute vitesseAttaque.
		 * @param vitesseAttaque
		 */
		public void setVitesseAttaque(int vitesseAttaque) {
		    this.vitesseAttaque = vitesseAttaque;
		}
		
		/**
		 * Return porteeVision.
		 * @return porteeVision
		 */
		public double getPorteeVision() {
		    return porteeVision;
		}
		
		/**
		 * Set a value to attribute porteeVision.
		 * @param porteeVision
		 */
		public void setPorteeVision(double porteeVision) {
		    this.porteeVision = porteeVision;
		}
		
		
		/**
		 * Description of the method calculerUnitePlusProche.
		 *
		 * @return ret
		 */
		public Unite calculerUnitePlusProche() {
			// Start of user code for method calculerUnitePlusProche

			Unite ret = null;

			return ret;
			// End of user code
		}

		/**
		 * Description of the method attaquer.
		 *
		 * @param cible
		 */
		public void attaquer(Unite cible) {
			// Start of user code for method attaquer

			// End of user code
		}

		/**
		 * Description of the method calculerDistance.
		 *
		 * @param ennemie
		 * @return ret
		 */
		public double calculerDistance(Unite ennemie) {
			// Start of user code for method calculerDistance

			double ret = 0;

			return ret;
			// End of user code
		}

		/**
		 * Description of the method guetter.
		 *
		 */
		public void guetter() {
			// Start of user code for method guetter

			// End of user code
		}
		
		// Start of user code to add methods for Unite
		
		// End of user code
}