/**
 * model/Attaquant.java
 *
 * File generated from the Attaquant uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 2/26/14 2:00:36 PM (February 26, 2014) $
 */
package model.agents;

// Start of user code to add imports for Attaquant
 

// End of user code

import model.environment.Case;
import model.environment.CaseLibre;

/**
 * Description of the class Attaquant.
 *
 */

public class Attaquant extends Unite implements UniteLibre {
		private int vitesse;
		
		// Start of user code to add fields for Attaquant
		 
		// End of user code
		
		/**
		 * Constructor.
		 */
        public Attaquant(int pv, int pt, int pa, int t, int va, double po, Case c, int v) {
        // Start of user code for constructor Unite
        super(pv, pt, pa, t, va, po, c);
        this.vitesse = v;
        // End of user code
        }
		
		/**
		 * Return vitesse.
		 * @return vitesse
		 */
		public int getVitesse() {
		    return vitesse;
		}
		
		/**
		 * Set a value to attribute vitesse.
		 * @param vitesse
		 */
		public void setVitesse(int vitesse) {
		    this.vitesse = vitesse;
		}

        /**
         * Description of the method seDeplacer.
        *
        * @param caseLibre
        */
        @Override
        public void seDeplacer(CaseLibre caseLibre) {

        }

        /**
         * Description of the method seDeplacerCase.
         *
         * @param caseAdjacente
         */
        @Override
        public void seDeplacerCase(CaseLibre caseAdjacente) {

        }

        /**
         * Description of the method suivreUnite.
         *
         * @param cible
         */
        @Override
        public void suivreUnite(UniteLibre cible) {

        }

        /**
         * Description of the method reagir.
         */
        @Override
        public void reagir() {

        }


        // Start of user code to add methods for Attaquant

        // End of user code
}