/**
 * model/Defenseur.java
 *
 * File generated from the Defenseur uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 2/26/14 2:00:36 PM (February 26, 2014) $
 */
package model.agents;

// Start of user code to add imports for Defenseur
 

// End of user code

/**
 * Description of the class Defenseur.
 *
 */

public class Defenseur extends Unite {
		
		// Start of user code to add fields for Defenseur
		 
		// End of user code
		
		/**
		 * Constructor.
		 */
		public Defenseur() {
			// Start of user code for constructor Defenseur
			super();
			// End of user code
		}
		
		
		
		// Start of user code to add methods for Defenseur
		
		// End of user code
}