/**
 * model/Defenseur.java
 *
 * File generated from the Defenseur uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 2/26/14 2:00:36 PM (February 26, 2014) $
 */
package model.agents;

// Start of user code to add imports for Defenseur
 

// End of user code

import model.environment.Case;

/**
 * Description of the class Defenseur.
 *
 */

public class Defenseur extends Unite {
		
		// Start of user code to add fields for Defenseur
		 
		// End of user code
		
		/**
		 * Constructor.
		 */
        public Defenseur(int pv, int pt, int pa, int t, int va, double po, Case c) {
            // Start of user code for constructor Unite
            super(pv, pt, pa, t, va, po, c);
            // End of user code
        }
		
		
		
		// Start of user code to add methods for Defenseur
		
		// End of user code
}