/**
 * model/Carte.java
 *
 * File generated from the Carte uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 2/26/14 2:00:37 PM (February 26, 2014) $
 */
package model.environment;

// Start of user code to add imports for Carte
 
import java.util.HashSet;

// End of user code

/**
 * Description of the class Carte.
 *
 */

public class Carte {
		private int hauteur;
		private int largeur;
		private HashSet<Case> cases;
		private HashSet<Arete> aretes;
		
		// Start of user code to add fields for Carte
		 
		// End of user code
		
		/**
		 * Constructor.
		 */
		public Carte() {
			// Start of user code for constructor Carte
			super();
			// End of user code
		}
		
		/**
		 * Return hauteur.
		 * @return hauteur
		 */
		public int getHauteur() {
		    return hauteur;
		}
		
		/**
		 * Set a value to attribute hauteur.
		 * @param hauteur
		 */
		public void setHauteur(int hauteur) {
		    this.hauteur = hauteur;
		}
		
		/**
		 * Return largeur.
		 * @return largeur
		 */
		public int getLargeur() {
		    return largeur;
		}
		
		/**
		 * Set a value to attribute largeur.
		 * @param largeur
		 */
		public void setLargeur(int largeur) {
		    this.largeur = largeur;
		}
		
		/**
		 * Return cases.
		 * @return cases
		 */
		public HashSet<Case> getCases() {
		    return cases;
		}
		
		/**
		 * Set a value to attribute cases.
		 * @param cases
		 */
		public void setCases(HashSet<Case> cases) {
		    this.cases = cases;
		}
		
		/**
		 * Add a cases to the cases collection.
		 * @param cases_elt Element to add.
		 */
		public void addCases(Case cases_elt) {
		    this.cases.add(cases_elt);
		}
		
		/**
		 * Remove a cases to the cases collection.
		 * @param cases_elt Element to remove
		 */
		public void removeCases(Case cases_elt) {
		    this.cases.remove(cases_elt);
		}
		
		/**
		 * Return aretes.
		 * @return aretes
		 */
		public HashSet<Arete> getAretes() {
		    return aretes;
		}
		
		/**
		 * Set a value to attribute aretes.
		 * @param aretes
		 */
		public void setAretes(HashSet<Arete> aretes) {
		    this.aretes = aretes;
		}
		
		/**
		 * Add a aretes to the aretes collection.
		 * @param aretes_elt Element to add.
		 */
		public void addAretes(Arete aretes_elt) {
		    this.aretes.add(aretes_elt);
		}
		
		/**
		 * Remove a aretes to the aretes collection.
		 * @param aretes_elt Element to remove
		 */
		public void removeAretes(Arete aretes_elt) {
		    this.aretes.remove(aretes_elt);
		}
		
		
		
		// Start of user code to add methods for Carte
		
		// End of user code
}