/**
 * model/Case.java
 *
 * File generated from the Case uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 2/26/14 2:00:36 PM (February 26, 2014) $
 */
package environment;

// Start of user code to add imports for Case


// End of user code

import agents.Unite;

import java.util.HashSet;

/**
 * Description of the class Case.
 *
 */

public class Case {

    // Start of user code to add fields for Case
    final private int capacite = 1;
    private Ressource ressource;
    private boolean obstacle;
    private boolean libre;
    private HashSet<Unite> unites;
    // End of user code

    /**
     * Constructor.
     */
    public Case() {
        // Start of user code for constructor Case
        super();
        unites = new HashSet<Unite>();
        // End of user code
    }

    public boolean estLibre() {
        return ressource != null && unites.size() < capacite;
    }

    public boolean estObstacle() {
        return ressource == null;
    }

    public void ajouterUnite(Unite unite) {
        unites.add(unite);
    }

    public void retirerUnite(Unite unite) {
        unites.remove(unite);
    }

    public boolean contientUnite(Unite unite) {
        return unites.contains(unite);
    }

    public int compte() {
        return unites.size();
    }





    // Start of user code to add methods for Case

    // End of user code
}