/**
 * model/Position.java
 *
 * File generated from the Position uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 2/26/14 2:00:36 PM (February 26, 2014) $
 */
package environment;

// Start of user code to add imports for Position
 

// End of user code

/**
 * Description of the class Position.
 *
 */

public class Position {
		final int posX;
		final int posY;
		
		// Start of user code to add fields for Position
		 
		// End of user code
		
		/**
		 * Constructor.
		 */
		public Position(int x, int y) {
			// Start of user code for constructor Position
			super();
            this.posX = x;
            this.posY = y;
			// End of user code
		}
		
		/**
		 * Return posX.
		 * @return posX
		 */
		public int getPosX() {
		    return posX;
		}

		
		/**
		 * Return posY.
		 * @return posY
		 */
		public int getPosY() {
		    return posY;
		}

		
		
		
		// Start of user code to add methods for Position
		
		// End of user code
}