/**
 * model/Base.java
 *
 * File generated from the Base uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 2/26/14 2:00:36 PM (February 26, 2014) $
 */
package agents;

// Start of user code to add imports for Base
 
import environment.Case;

import java.util.HashSet;

// End of user code

/**
 * Description of the class Base.
 *
 */

public class Base extends Agent  {
		private int bois;
		private int nourriture;
		private int pv;
		private HashSet<Unite> unites;
		private String nom;
		
		// Start of user code to add fields for Base
		 
		// End of user code
		
		/**
		 * Constructor.
		 */
		public Base(int bois, int nourriture, int pv, String nom) {
			// Start of user code for constructor Base
			super(pv);
            this.bois = bois;
            this.nourriture = nourriture;
            this.nom = nom;
			// End of user code
		}
		
		/**
		 * Return bois.
		 * @return bois
		 */
		public int getBois() {
		    return bois;
		}
		
		/**
		 * Set a value to attribute bois.
		 * @param bois
		 */
		public void setBois(int bois) {
		    this.bois = bois;
		}
		
		/**
		 * Return nourriture.
		 * @return nourriture
		 */
		public int getNourriture() {
		    return nourriture;
		}
		
		/**
		 * Set a value to attribute nourriture.
		 * @param nourriture
		 */
		public void setNourriture(int nourriture) {
		    this.nourriture = nourriture;
		}
		
		/**
		 * Return pv.
		 * @return pv
		 */
		public int getPv() {
		    return pv;
		}
		
		/**
		 * Set a value to attribute pv.
		 * @param pv
		 */
		public void setPv(int pv) {
		    this.pv = pv;
		}
		
		/**
		 * Return unites.
		 * @return unites
		 */
		public HashSet<Unite> getUnites() {
		    return unites;
		}
		
		/**
		 * Set a value to attribute unites.
		 * @param unites
		 */
		public void setUnites(HashSet<Unite> unites) {
		    this.unites = unites;
		}
		
		/**
		 * Add a unites to the unites collection.
		 * @param unites_elt Element to add.
		 */
		public void addUnites(Unite unites_elt) {
		    this.unites.add(unites_elt);
		}
		
		/**
		 * Remove a unites to the unites collection.
		 * @param unites_elt Element to remove
		 */
		public void removeUnites(Unite unites_elt) {
		    this.unites.remove(unites_elt);
		}
		
		/**
		 * Return nom.
		 * @return nom
		 */
		public String getNom() {
		    return nom;
		}
		
		/**
		 * Set a value to attribute nom.
		 * @param nom
		 */
		public void setNom(String nom) {
		    this.nom = nom;
		}
		
		
		/**
		 * Description of the method creerUnite.
		 *
		 * @param choix
		 * @param nombre
		 */
		public void creerUnite(int choix, int nombre) {
			// Start of user code for method creerUnite

			// End of user code
		}

		/**
		 * Description of the method deplacerUnites.
		 *
		 * @param listeUnites
		 * @param caseLibre
		 */
		public void deplacerUnites(IUniteLibre listeUnites, Case caseLibre) {
			// Start of user code for method deplacerUnites
            double k;
			// End of user code
		}

		/**
		 * Description of the method jouer.
		 *
		 */
		public void jouer() {
			// Start of user code for method jouer

			// End of user code
		}

        /**
         * Description of the method reagir.
         */
        @Override
        public void reagir() {

        }

        // Start of user code to add methods for Base
		
		// End of user code
}